name: Build and Smoke test

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Create .env file
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> .env
          # Add any other non-secret variables needed for the build.
          echo "POSTGRES_USER=postgres" >> .env
          echo "POSTGRES_DB=postgres" >> .env


      - name: Build Docker images
        run: docker compose build

      - name: Start services
        run: docker compose up -d

      - name: Wait for services to be ready
        run: sleep 15

      - name: Test backend health endpoint
        run: curl --fail http://localhost:8000/api/test

      - name: Test frontend is responding
        run: curl --fail http://localhost:5173

      - name: Shutdown services
        if: always() # Ensure services are stopped even if previous steps fail
        run: docker compose down -v --remove-orphans