name: Continuous Integration

on:
push:
  branches: ["main"]

pull_request:
  branches: ["main"]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

  steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    #Verifies that the Dockerfile is correct and all dependencies can be installed
    - name: build backend image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        dockerfile: ./backend/Dockerfile 
        load: true #Load the image into the Docker daemon, don't push to a registry yet
        tags: pathfinder-backend:ci

    # Runs our tests if the dockerfile is configured to do so but for now validates image can be built successfully
    - name: build frontend image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        dockerfile: ./frontend/Dockerfile 
        load: true 
        tags: pathfinder-frontend:ci